name: publish

on:
    workflow_dispatch: # Allow running the workflow manually from the GitHub UI
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
        branches:
            - 'feature/zoe-actions' # Run the workflow when pushing to the main branch
            - 'main'
        paths:
            - 'src/**'
    pull_request:
        branches:
            - '*' # Run the workflow for all pull requests
    release:
        types:
            - published # Run the workflow when a new GitHub release is published
defaults:
    run:
        shell: pwsh
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build  ./src/ChatUAISDK/ChatUAISDK.csproj  --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      - name: Create the package
        run: dotnet pack ./src/ChatUAISDK/ChatUAISDK.csproj   --configuration release -o:${{ env.NuGetDirectory }} /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
      - name: Publish the package to GPR
        run: dotnet nuget push ./src/ChatUAISDK/bin/Release/*.nupkg  --api-key "${{ secrets.TEST_CHATU_NUGET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate

